#!/bin/sh

cmd=$(which tmux) # tmux path
session=coding    # session name

if [ -z $cmd ]; then
  echo "You need to install tmux."
  exit 1
fi

$cmd has -t $session

if [ $? != 0 ]; then
  # setup octoly session
  $cmd new-session -s $session -d -n neffos
  $cmd send-keys "cd ~/neffos/mt6757_7.1/alps/kernel-4.4" Enter
  $cmd send-keys 'vim drivers/input/touchscreen/mediatek/FT8716/focaltech_core.c ' Enter

  $cmd split-window -h -p 50
  $cmd send-keys "cd ~/neffos/mt6757_7.1/alps" Enter
  $cmd send-keys "bash" Enter
  $cmd send-keys "source build/envsetup.sh" Enter
  $cmd send-keys "lunch 25" Enter
  $cmd split-window -v -p 50
  $cmd send-keys 'ls ' Enter

  # Select vim pane
  $cmd select-pane -t 1

  # create second window
  $cmd new-window -n tmp
  $cmd send-keys 'htop' Enter

  # create third window
  $cmd new-window -n git
  $cmd send-keys 'cd ~/github' Enter

  # Optional step, reselect window 1 (the one with vim)
  $cmd select-window -t neffos

fi

$cmd att -t $session

exit 0
